#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

missing=()

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    missing+=("$1")
  fi
}

need_command ruby
need_command gem

if [ "${#missing[@]}" -gt 0 ]; then
  echo "Missing required command(s): ${missing[*]}" >&2
  echo "Install Ruby first, then rerun ./install.sh." >&2
  echo "Debian/Ubuntu: sudo apt install ruby-full build-essential zlib1g-dev" >&2
  echo "macOS: brew install ruby" >&2
  exit 1
fi

if ! command -v bundle >/dev/null 2>&1; then
  echo "Installing Bundler..."
  gem install bundler
fi

if ! ruby -rnet/ftp -e true >/dev/null 2>&1; then
  echo "Installing net-ftp for native gem builds..."
  gem install net-ftp
fi

mkdir -p .bundle
LOCAL_GEMFILE="Gemfile.local"
LOCAL_CONFIG=".bundle/_config.local.yml"

for local_file in "$LOCAL_GEMFILE" "${LOCAL_GEMFILE}.lock"; do
  if ! grep -qxF "$local_file" .git/info/exclude; then
    printf '%s\n' "$local_file" >> .git/info/exclude
  fi
done

{
  sed 's/^gem "github-pages".*/gem "github-pages", "~> 232"/' Gemfile
  printf '\n# Local Ruby compatibility overrides generated by install.sh.\n'
  printf 'gem "nokogiri", ">= 1.16", "< 2.0"\n'
  printf 'gem "kramdown-math-katex"\n'
} > "$LOCAL_GEMFILE"

cat > "$LOCAL_CONFIG" <<'YAML'
exclude:
  - .bundle
  - vendor
  - Gemfile
  - Gemfile.lock
  - Gemfile.local
  - Gemfile.local.lock
  - install.sh
  - run.sh
  - README.md
  - tool/src
  - tool/node_modules
  - tool/package.json
  - tool/package-lock.json
  - tool/tsconfig.json
  - tool/vite.config.ts
  - tool/README.md
  - tool/metadata.json
YAML

echo "Installing Jekyll gems into .bundle/vendor..."
bundle config set --local path '.bundle/vendor'
bundle config set --local gemfile "$LOCAL_GEMFILE"
BUNDLE_GEMFILE="$LOCAL_GEMFILE" bundle install

# Keep the tracked run.sh first-run check from rewriting local Bundler config.
mkdir -p vendor/bundle

if [ -f tool/package.json ]; then
  if command -v npm >/dev/null 2>&1; then
    echo "Installing tool dependencies..."
    (
      cd tool
      npm install
    )
  else
    echo "npm not found; skipping tool dependencies." >&2
    echo "Install Node.js/npm if you need to build or run ./tool." >&2
  fi
fi

echo "Install complete."
echo "Run the site with: BUNDLE_GEMFILE=$LOCAL_GEMFILE ./run.sh"
